### ISSUE TITLE
plz, provide an .apk foe those, that do not have google play market on their devices

### ISSUE THREAD

**Issue by vovkav** [chislon/LegacyLauncher#2]
plz, provide an .apk foe those, that do not have google play market on their devices

**Comment by chislon** [comment]
Uploaded v0.39.6 APK pulled from the Play Store. Hopefully this works for you: 
https://github.com/chislon/LegacyLauncher/downloads

**Comment by chislon** [comment]
New URL: http://sourceforge.net/projects/legacylauncher/files/published/

Github downloads is shutting down
