### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by dalb8** [chislon/LegacyLauncher#3]
I tried to build at 05d46328ab5 by polar bear and I get 53 errors beginning with:
`LegacyLauncher/src/com/wordpress/chislonchow/legacylauncher/DragLayer.java:450: cannot find symbol
    [javac] symbol  : variable mScrollX
    [javac] location: class com.wordpress.chislonchow.legacylauncher.DragLayer
    [javac]             final int scrollX = mScrollX;
    [javac]                                 ^
`

I contribute to the f-droid.org repository . We have ADW launcher but since it is no longer a free software project , we would like to replace it with something that is free and still being worked on.

**Comment by chislon** [comment]
Like most Launcher branches, it has to be built with hidden/internal APIs: http://stackoverflow.com/questions/7888191/how-do-i-build-the-android-sdk-with-hidden-and-internal-apis-available
